[package]
name = "ui"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow.workspace = true
dyn-clone = "1.0.14"
gpui2 = { path = "../gpui2" }
serde.workspace = true
settings = { path = "../settings" }
smallvec.workspace = true
strum = { version = "0.25.0", features = ["derive"] }
theme = { path = "../theme" }
